#! /bin/bash

set -euo pipefail
set -x

filter_redundant_monkeyc_warnings() {
    grep -v "^WARNING: .*: The launcher icon (128x128) isn't compatible with the specified launcher icon size of the device .*\. Image will be scaled to the target size" |
        grep -v "^WARNING: .*: Glance applications are not supported for app type 'watch-app' on device .*\. The glance annotation will be ignored.$" ||
        true
}

exec > >(filter_redundant_monkeyc_warnings) 2>&1

latest_sdk_version="6.4.2-2024-01-04-a1dd13ee0"
stable_sdk_version="6.4.2-2024-01-04-a1dd13ee0"

developer_key=~/Workbench/Garmin/developer_key

sdks_dir=~/Library/Application\ Support/Garmin/ConnectIQ/Sdks
latest_sdk_root="$sdks_dir/connectiq-sdk-mac-$latest_sdk_version"
stable_sdk_root="$sdks_dir/connectiq-sdk-mac-$stable_sdk_version"

dev_devices=(
    fenix7
    fr955
    vivoactive4
    fr645m
)

for device in "${dev_devices[@]}"; do
    java -Xms1g -Dfile.encoding=UTF-8 -Dapple.awt.UIElement=true \
        -jar "$latest_sdk_root"/bin/monkeybrains.jar \
        -o release/"$device"/WatchApp-"$device".prg \
        -f monkey.jungle \
        -y "$developer_key" \
        -d "$device" \
        -w
done

java -Xms1g -Dfile.encoding=UTF-8 -Dapple.awt.UIElement=true \
    -jar "$stable_sdk_root"/bin/monkeybrains.jar \
    -o release/iq/WatchApp.iq \
    -f monkey.jungle \
    -y "$developer_key" \
    -e \
    -r \
    -w
