package com.gentin.connectiq.handsfree.terms

const val muteInCmd = "m"
const val setAudioVolumeInCmd = "v"
const val callV1InCmd = "call"
const val callInCmd = "c"
const val hangUpV1InCmd = "hangup"
const val hangUpInCmd = "h"
const val acceptV1InCmd = "accept"
const val acceptInCmd = "a"
const val syncMeV1InCmd = "syncMe"
const val syncPhonesV1InCmd = "syncPhones"
const val queryInCmd = "q"
const val openMeInCmd = "o"
const val openAppInStoreInCmd = "r"
const val didFirstLaunchInCmd = "l"
const val toggleSpeakerInCmd = "p"
