#!/usr/bin/env python3

"""Generate language-specific Jungle override fragments.

This script reads the declared languages from one or more Connect IQ manifests
and writes `base.lang.<lang>` overrides to an explicit output path.

The generated resource path is derived relative to the output file location,
so `local/lang-resources.jungle` points at `resources-<lang>` under `local/`
and `build/lang-resources.jungle` points at `resources-<lang>` under `build/`.
Only non-English languages are emitted.
"""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Iterable


CONNECT_IQ_NS = {"iq": "http://www.garmin.com/xml/connectiq"}


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    repo_root = Path(__file__).resolve().parent.parent

    parser = argparse.ArgumentParser(
        description="Generate a Jungle file with language-specific overrides."
    )
    parser.add_argument(
        "--manifest",
        action="append",
        default=None,
        type=Path,
        help=(
            "Manifest path used to discover enabled languages. Repeat to add "
            "multiple manifests. Defaults to manifest-app.xml and manifest-widget.xml."
        ),
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Path to the generated Jungle file.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated Jungle content instead of writing it.",
    )
    parser.set_defaults(repo_root=repo_root)
    return parser.parse_args()


def resolve_manifest_paths(repo_root: Path, manifest_paths: list[Path] | None) -> list[Path]:
    """Resolve manifest paths relative to the repository root."""
    manifest_specs = manifest_paths or [Path("manifest-app.xml"), Path("manifest-widget.xml")]
    resolved_paths: list[Path] = []

    for manifest_path in manifest_specs:
        resolved_path = manifest_path if manifest_path.is_absolute() else repo_root / manifest_path
        resolved_paths.append(resolved_path.resolve())

    return resolved_paths


def load_manifest_languages(manifest_paths: Iterable[Path]) -> list[str]:
    """Load declared languages from manifests, preserving first-seen order."""
    languages: list[str] = []
    seen: set[str] = set()

    for manifest_path in manifest_paths:
        if not manifest_path.exists():
            raise SystemExit(f"Manifest not found: {manifest_path}")

        try:
            tree = ET.parse(manifest_path)
        except ET.ParseError as exc:
            raise SystemExit(f"Failed to parse {manifest_path}: {exc}") from exc

        for element in tree.findall(".//iq:languages/iq:language", CONNECT_IQ_NS):
            language = (element.text or "").strip()
            if not language or language in seen:
                continue
            seen.add(language)
            languages.append(language)

    if "eng" not in seen:
        languages.insert(0, "eng")

    return languages


def build_language_components(output_path: Path, language: str) -> list[str]:
    """Return the resource path components for one language.

    The generated jungle file is expected to live next to resources-<lang>.
    """

    sibling_resource_dir = output_path.parent / f"resources-{language}"
    if not sibling_resource_dir.exists():
        return []
    return [f"resources-{language}"]


def render_jungle(output_path: Path, languages: Iterable[str]) -> str:
    """Render the final Jungle content."""
    lines = [
        "# Auto-generated by Scripts/generate_lang_jungle.py\n",
        "# DO NOT EDIT\n",
    ]

    emitted_any = False
    for language in languages:
        if language == "eng":
            continue

        components = build_language_components(output_path, language)
        if not components:
            continue

        emitted_any = True
        lines.append(
            f"base.lang.{language} = $(base.lang.{language});{';'.join(components)}\n"
        )

    if not emitted_any:
        lines.append("# No non-English language overrides were generated.\n")

    return "".join(lines)


def main() -> int:
    """Generate a language override Jungle file."""
    args = parse_args()
    repo_root: Path = args.repo_root
    manifest_paths = resolve_manifest_paths(repo_root, args.manifest)
    output_path = args.output if args.output.is_absolute() else (repo_root / args.output).resolve()
    languages = load_manifest_languages(manifest_paths)
    output = render_jungle(output_path, languages)

    if args.dry_run:
        sys.stdout.write(output)
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())