#!/usr/bin/env python3

"""Generate per-device strings.xml files and a matching Jungle override file.

The generated resource directories can be referenced from the generated
device-id.jungle to expose a per-device string resource, defaulting to:

    <string id="deviceId">{device_id}</string>

By default this compares manifest-app.xml and manifest-widget.xml, writes one
resource directory per device present in either manifest under
jungle/generated/device-id-resources, and writes
the Jungle overrides to jungle/generated/device-id.jungle.
"""

from __future__ import annotations

import argparse
import os
import shutil
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from xml.sax.saxutils import escape

from list_common_manifest_devices import get_manifest_device_ids


CONNECT_IQ_NS = {"iq": "http://www.garmin.com/xml/connectiq"}


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for device resource generation."""
    repo_root = Path(__file__).resolve().parent.parent

    parser = argparse.ArgumentParser(
        description="Generate per-device strings.xml resources and a Jungle file."
    )
    parser.add_argument(
        "manifest_a",
        nargs="?",
        default=repo_root / "manifest-app.xml",
        type=Path,
        help="First manifest to compare.",
    )
    parser.add_argument(
        "manifest_b",
        nargs="?",
        default=repo_root / "manifest-widget.xml",
        type=Path,
        help="Second manifest to compare.",
    )
    parser.add_argument(
        "--resources-root",
        default=repo_root / "jungle/generated/device-id-resources",
        type=Path,
        help="Directory where per-device resource folders will be generated.",
    )
    parser.add_argument(
        "--jungle-output",
        default=repo_root / "jungle/generated/device-id.jungle",
        type=Path,
        help="Path to the generated Jungle override file.",
    )
    parser.add_argument(
        "--string-id",
        default="deviceId",
        help="String resource id to generate in each strings.xml file.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove existing generated resources root before regenerating.",
    )
    return parser.parse_args()


def render_strings_xml(string_id: str, device_id: str) -> str:
    """Render a minimal strings.xml containing the device id."""
    escaped_string_id = escape(string_id, {'"': '&quot;'})
    escaped_device_id = escape(device_id)
    return (
        "<resources>\n"
        f"    <string id=\"{escaped_string_id}\" scope=\"glance\">{escaped_device_id}</string>\n"
        f"    <string id=\"{escaped_string_id}\" scope=\"background\">{escaped_device_id}</string>\n"
        "</resources>\n"
    )


def load_manifest_languages(manifest_path: Path) -> set[str]:
    """Load all declared language ids from a Connect IQ manifest file."""
    if not manifest_path.exists():
        raise SystemExit(f"Manifest not found: {manifest_path}")

    try:
        tree = ET.parse(manifest_path)
    except ET.ParseError as exc:
        raise SystemExit(f"Failed to parse {manifest_path}: {exc}") from exc

    languages = {
        (element.text or "").strip()
        for element in tree.findall(".//iq:languages/iq:language", CONNECT_IQ_NS)
        if (element.text or "").strip()
    }

    return languages or {"eng"}


def write_device_resources(
    resources_root: Path,
    device_ids: list[str],
    string_id: str,
) -> None:
    """Write one default strings.xml file per device under the resources root."""
    resources_root.mkdir(parents=True, exist_ok=True)

    for device_id in device_ids:
        target_dir = resources_root / device_id
        target_dir.mkdir(parents=True, exist_ok=True)
        (target_dir / "strings.xml").write_text(
            render_strings_xml(string_id, device_id),
            encoding="utf-8",
        )


def os_path_relpath(target_path: Path, start_path: Path) -> str:
    """Return a filesystem relative path string between two paths."""
    return os.path.relpath(target_path, start_path)


def render_jungle(
    resources_root: Path,
    jungle_output: Path,
    device_ids: list[str],
    languages: list[str],
) -> str:
    """Render Jungle overrides mapping each device and language to one folder."""
    lines = [
        "# Auto-generated by Scripts/generate_device_id_resources.py\n",
        "# Adds per-device resource directories that contain strings.xml.\n",
        "\n",
    ]

    for device_id in device_ids:
        resource_path = Path(
            os_path_relpath(resources_root / device_id, jungle_output.parent)
        ).as_posix()
        lines.append(
            f"{device_id}.resourcePath = $({device_id}.resourcePath);{resource_path}\n"
        )

        for language in languages:
            if language == "eng":
                continue

            lines.append(
                f"{device_id}.lang.{language} = $({device_id}.lang.{language});{resource_path}\n"
            )

    return "".join(lines)


def validate_string_id(string_id: str) -> None:
    """Validate the generated resource id is safe for XML output."""
    if not string_id:
        raise SystemExit("--string-id must not be empty")

    if any(character.isspace() for character in string_id):
        raise SystemExit("--string-id must not contain whitespace")


def main() -> int:
    """Generate per-device strings.xml files and the matching Jungle file."""
    args = parse_args()
    validate_string_id(args.string_id)

    device_ids = get_manifest_device_ids(args.manifest_a, args.manifest_b)
    languages = sorted(
        load_manifest_languages(args.manifest_a) | load_manifest_languages(args.manifest_b)
    )

    if args.clean and args.resources_root.exists():
        shutil.rmtree(args.resources_root)

    write_device_resources(args.resources_root, device_ids, args.string_id)

    args.jungle_output.parent.mkdir(parents=True, exist_ok=True)
    args.jungle_output.write_text(
        render_jungle(args.resources_root, args.jungle_output, device_ids, languages),
        encoding="utf-8",
    )

    print(f"Generated {len(device_ids)} device resource folders in {args.resources_root}")
    print(f"Generated Jungle overrides in {args.jungle_output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
