#! /bin/bash

set -x
set -euo pipefail

wd=$(dirname "$0")
prg_dir="$wd/../../build/prg"

bucket="handsfree.prg.beta"

aws s3 rm "s3://$bucket"/ --recursive

aws s3 cp \
    "$prg_dir" \
    "s3://$bucket"/ \
    --recursive \
    --exclude '*' \
    --include 'index.html' \
    --include '**/*.prg' \
    --include '**/*-settings.json' \
    --include '**/*.prg.debug.xml' \
    --include '**/Handsfree-beta-*.TXT'
