#! /bin/bash

set -x
set -euo pipefail

wd=$(dirname "$0")
prg_dir="$wd/../../build/prg"

bucket="handsfree.prg.beta"

aws s3 rm "s3://$bucket"/ --recursive

aws s3 cp \
    "$prg_dir" \
    "s3://$bucket"/ \
    --recursive \
    --include '*.xml' \
    --exclude '**/mir/*' \
    --exclude '**/internal-mir/*' \
    --exclude '*.mc' \
    --exclude '**/gen/*'
