#! /bin/bash

set -x
set -euo pipefail
shopt -s nullglob

api_token="$POEDITOR_TOKEN"
project_id="691894"

tmpdir=$(mktemp -d /tmp/push-markdown.XXXXX)

push_json() {
    local json="$1"

    curl -X POST https://api.poeditor.com/v2/terms/add \
        --fail-with-body \
        -w "\n" \
        -d api_token="$api_token" \
        -d id="$project_id" \
        -d language="en" \
        --data-urlencode data@"$json"
    curl -X POST https://api.poeditor.com/v2/translations/add \
        --fail-with-body \
        -w "\n" \
        -d api_token="$api_token" \
        -d id="$project_id" \
        -d language="en" \
        --data-urlencode data@"$json"
    curl -X POST https://api.poeditor.com/v2/translations/update \
        --fail-with-body \
        -w "\n" \
        -d api_token="$api_token" \
        -d id="$project_id" \
        -d language="en" \
        --data-urlencode data@"$json"
}

for i in extras/In-App-Markdown/Onboarding/*.md; do
    echo "Uploading $i"
    suffix=$(basename "$i" .md | tr '-' '_' | tr '[:upper:]' '[:lower:]')
    term="onboarding_$suffix"
    json="$tmpdir/$term.json"
    jq -n -cr --rawfile data "$i" '[{term: "'"$term"'", translation:{content: $data}}]' >"$json"
    push_json "$json"
done

for i in extras/In-App-Markdown/Settings/*.md; do
    echo "Uploading $i"
    suffix=$(basename "$i" .md | tr '-' '_' | tr '[:upper:]' '[:lower:]')
    term="settings_$suffix"
    json="$tmpdir/$term.json"
    app/push-strings-from-markdown.main.kts "$i" >"$json"
    push_json "$json"
done
