#! /bin/bash

set -x
set -euo pipefail

adb_device="$1" # e.g. localhost:5555 or emulator-5554
shift

adb -s "$adb_device" shell content query --uri content://com.android.contacts/data/phones
adb -s "$adb_device" shell content query --uri content://call_log/calls
