#! /bin/bash

set -x
set -euo pipefail

# Add a keyboard shortcut to delete all apps in the simulator (Cmd+D)
defaults write com.garmin.connectiq.simulator NSUserKeyEquivalents -dict-add 'Delete All Apps' '@d'
