#! /bin/bash

set -x
set -euo pipefail

iq="$1"
shift

adb_device="$1" # e.g. localhost:5555
shift

wd=$(dirname "$0")

src_root="$wd"/../..

adb connect "$adb_device"
adb -s "$adb_device" forward tcp:7381 tcp:7381

"$src_root"/extras/Publishing/for-each-prg-in-iq \
    "$iq" \
    "$wd"/Run-prg-exp \
    "$wd"/PayloadTest.exp
