#! /bin/bash

set -x
set -euo pipefail

device="$1"
shift

wd=$(dirname "$0")
src_root="$wd"/../..

adb -s "$device" install -t "$src_root"/app/build/intermediates/apk/selfHosted/debug/app-selfHosted-debug.apk
